apiVersion: v1
kind: Secret
metadata:
  name: helloworld-secrets
type: Opaque
data:
  username: cm9vdAo=
  password: TXlwYXNzd29yZEAxMjMK
  rootPassword: TXlwYXNzd29yZEAxMjMK
  database: ZW1wbG95ZWVkYgo=
